# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f5c462528214d1d92779e39c3a562924d3df11015d3bfd7b3b117a710e78db6b15743d4034ef40d2c71120bf4d345f3cd152467ab3e95b0eb52bd9132741deb1

test:
  secret_key_base: b0863fb7ccfbcf06804df0ec9b3a5ac0444685adf215bc22a1d16becc46d81262f2b9039de692d9199ea8e19152cc20bcee61a6fc25867735bfdfc21aab7d1f8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
