# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2469e2c4a0e8a6f95ee40abd96301d752c33f1f015ee7ba45c295109f67789bbd2f631146cea2c26eaa39573722a44b15f9fe1d6750d44fb837aae104d8c95fb

test:
  secret_key_base: 97c58e930ea555d0bff4e261f7968a88456eb6ad92ddf1a2e089240b185c5109c275ebb394da1fc0b77ede23026c30dcd5c27cb5d44840e5842a18ab002dc187

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
